# ==========================================================
# Project Name / GitHub Actions Workflow Name
# This name appears in the GitHub Actions tab
# ==========================================================
name: irctc-prod ## $Project Name / $Branch

# ==========================================================
# Trigger Workflow
# Runs automatically whenever code is pushed to main branch
# ==========================================================
on:
  push:
    branches:
      - main ## CHANGE Branch Name HERE !!!

# ==========================================================
# Required Permissions for GitHub OIDC Authentication
# id-token: Used to assume AWS IAM Role
# contents: Read repository source code
# ==========================================================
permissions:
  id-token: write  ## NEEDED!!!
  contents: read

jobs:

  # ========================================================
  # Main CI/CD Job
  # ========================================================
  credentials_build_deploy:

    # Job Display Name
    name: Building and Pushing the Image

    # GitHub Hosted Runner
    # Can be changed to self-hosted/private runner
    runs-on: [ubuntu-latest] ## private/public runner

    steps:

    # ======================================================
    # Download Source Code from GitHub Repository
    # ======================================================
    - name: Checkout
      uses: actions/checkout@v4

    # ======================================================
    # Configure AWS Credentials using GitHub OIDC
    # Assumes IAM Role in AWS Account
    # ======================================================
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::738759745415:role/GitHubActionRolev1  # change AWS account HERE
        aws-region: us-east-1

    # ======================================================
    # Login to Amazon Elastic Container Registry (ECR)
    # ======================================================
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # ======================================================
    # Build Docker Image
    # Tag Docker Image
    # Push Docker Image to Amazon ECR
    # Update Kubernetes Deployment Manifest
    # ======================================================
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: eks-repo  ## CHANGE ECR Name HERE!!!
      run: |

        # Generate Short Commit ID
        IMAGE_TAG=$(git rev-parse --short "$GITHUB_SHA")

        # Environment Name
        ENV=prod                                   ## CHANGE Env Name HERE!!!

        # Extract Current Branch Name
        BRANCH=${GITHUB_REF##*/}

        # Build Docker Image
        docker build -f Dockerfile-$ENV \
        --build-arg ARG_ENV=${ENV} \
        -t $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH-$IMAGE_TAG .

        # Push Docker Image to ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH-$IMAGE_TAG

        # Print Image Tag
        echo $IMAGE_TAG

        # Move to Kubernetes Manifest Directory
        cd manifast/prod                                                             ## CHANGE DIR Name HERE!!!

        # Replace Placeholder Image Name in Deployment File
        sed -i "s|CHANGE-IMAGE-NAME|$ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH-$IMAGE_TAG|g" deployment.yaml

    # ======================================================
    # Connect kubectl to EKS Cluster
    # Updates ~/.kube/config
    # ======================================================
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region us-east-1 --name eks-cluster

    # ======================================================
    # Deploy Kubernetes Resources to EKS
    # Namespace → Deployment → Service → Ingress
    # ======================================================
    - name: Deploy to EKS with Customization
      run: |

        # Select EKS Cluster Context
        kubectl config use-context arn:aws:eks:us-east-1:738759745415:cluster/eks-cluster

        # Create Namespace
        kubectl apply -f manifast/prod/namespace.yaml

        # Deploy Application
        kubectl apply -f manifast/prod/deployment.yaml

        # Create Service
        kubectl apply -f manifast/prod/service.yaml

        # Create Ingress
        kubectl apply -f manifast/prod/ingress.yaml

        # Verify Service Creation
        kubectl get svc -n irctc-prod
        kubectl apply -f manifast/prod/deployment.yaml
        kubectl apply -f manifast/prod/service.yaml
        kubectl apply -f manifast/prod/ingress.yaml
        kubectl get svc -n k8s-prod                        #CHANGE
